//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonificaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int id_empleado { get; set; }
        public int documento_empleado { get; set; }
        public string nombre_empleado { get; set; }
        public int cargo_id { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
    
        public virtual Cargos Cargos { get; set; }
    }
}
